# Generated by Django 5.2.15 on 2026-06-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_is_active_users_is_staff_users_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('coach', 'Coach'), ('coachee', 'Coachee')], max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
