# Generated by Django 5.2.15 on 2026-06-30 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auth_roles_and_department_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachCoachee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachee_links', to=settings.AUTH_USER_MODEL)),
                ('coachee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('coach', 'coachee'), name='unique_coach_coachee_pair')],
            },
        ),
    ]
