# Generated by Django 5.2.15 on 2026-06-26 11:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.PositiveIntegerField(editable=False)),
                ('form_version', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=4)),
                ('form_name', models.TextField(help_text='Rich text (HTML) for form title')),
                ('frequency', models.IntegerField(choices=[(1, 'Annually'), (2, 'Quarterly'), (3, 'Monthly'), (4, 'Weekly'), (5, 'Daily'), (6, 'Adhoc'), (99, 'Other')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'form_types',
                'ordering': ['form_id', '-form_version'],
                'unique_together': {('form_id', 'form_version')},
            },
        ),
        migrations.CreateModel(
            name='FormSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=4)),
                ('subsection', models.TextField(help_text='Rich text (HTML) subsection heading')),
                ('form_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='forms.formtype')),
            ],
            options={
                'db_table': 'form_subsection',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=4)),
                ('question_id', models.CharField(blank=True, max_length=50, null=True)),
                ('question', models.TextField(help_text='Rich text (HTML) question text')),
                ('answer_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('multi_select', 'Multi Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('file', 'File')], max_length=50)),
                ('association_subsection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='forms.formsubsection')),
                ('form_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.formtype')),
            ],
            options={
                'db_table': 'form_questions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FormForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=4)),
                ('form_id', models.PositiveIntegerField()),
                ('form_version', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sequence_no', models.PositiveIntegerField()),
                ('user_entered', models.BooleanField(default=False)),
                ('paratext', models.TextField(blank=True, help_text='Rich text (HTML)', null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('auto_select_version', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('auto_select_text', models.TextField(blank=True, help_text='Rich text (HTML)', null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_items', to='forms.formquestion')),
                ('form_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_items', to='forms.formtype')),
            ],
            options={
                'db_table': 'form_forms',
                'ordering': ['sequence_no'],
            },
        ),
    ]
