# Generated by Django 4.2.7 on 2026-06-29 09:02

from django.db import migrations, models


def backfill_sequence_no(apps, schema_editor):
    FormQuestion = apps.get_model("forms", "FormQuestion")
    FormForm = apps.get_model("forms", "FormForm")

    form_form_sequence = {
        item.question_id: item.sequence_no
        for item in FormForm.objects.filter(question__isnull=False).only(
            "question_id", "sequence_no"
        )
    }

    grouped = {}
    for question in FormQuestion.objects.order_by("form_type_id", "version", "id"):
        key = (question.form_type_id, str(question.version))
        grouped.setdefault(key, []).append(question)

    for questions in grouped.values():
        for index, question in enumerate(questions, start=1):
            question.sequence_no = form_form_sequence.get(question.id, index)
            question.save(update_fields=["sequence_no"])


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_publish_and_submissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formquestion',
            options={'ordering': ['sequence_no', 'id']},
        ),
        migrations.AddField(
            model_name='formquestion',
            name='sequence_no',
            field=models.PositiveIntegerField(blank=True, help_text='Display order within the form version (lower = earlier)', null=True),
        ),
        migrations.RunPython(backfill_sequence_no, migrations.RunPython.noop),
    ]
