# Generated by Django 5.2.15 on 2026-07-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_formpagesubmission_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='is_required',
            field=models.BooleanField(default=False, help_text='If true, this question must be answered before the form can be submitted'),
        ),
    ]
