# Generated by Django 5.2.15 on 2026-07-02 11:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_add_is_required_to_formquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='version',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=4),
        ),
    ]
