# Generated by Django 4.2.7 on 2026-06-25 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, null=True)),
                ('file_path', models.CharField(max_length=1024, null=True)),
                ('file_type', models.CharField(max_length=100, null=True)),
                ('file_size', models.BigIntegerField(null=True)),
                ('file_info', models.JSONField(blank=True, null=True)),
                ('module_name', models.CharField(max_length=100, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
