# Generated by Django 4.2.7 on 2026-06-25 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_date', models.DateField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/media/')),
                ('document_type', models.CharField(max_length=200)),
                ('document_details', models.CharField(blank=True, max_length=100, null=True)),
                ('archieve_by', models.CharField(max_length=100, null=True)),
                ('archieve_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('document_url', models.TextField(null=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_divisions', models.CharField(max_length=100)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('addedDateAndTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updatedDateAndTime', models.DateTimeField(auto_now=True, null=True)),
                ('updated_fields', models.TextField(blank=True, null=True)),
                ('entity_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
