# Generated by Django 4.2.7 on 2026-06-25 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=20)),
                ('context', models.CharField(choices=[('workflow_assignment', 'Workflow Assignment'), ('email_workflow', 'Email Workflow Assignment'), ('generic', 'Generic')], default='generic', max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=200)),
                ('comments', models.TextField(blank=True, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True)),
                ('uptime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('step_seq_no', models.IntegerField(null=True)),
                ('step_process', models.CharField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ManyToManyField(blank=True, related_name='workstep_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('step_seq_no',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_json_data', models.JSONField(blank=True, null=True)),
                ('ticket_no', models.CharField(blank=True, max_length=100, null=True)),
                ('changefields', models.JSONField(blank=True, null=True)),
                ('current_step', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('workflow_status', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
                ('initiated_by', models.IntegerField(blank=True, null=True)),
                ('current_step_userids', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_data', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('workflow_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.workflowinstance')),
            ],
        ),
        migrations.AddField(
            model_name='workflow',
            name='workflow_step',
            field=models.ManyToManyField(blank=True, related_name='worksteps', to='workflow.workstep'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='workflow.notificationmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailWorkFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_function', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflow')),
            ],
        ),
    ]
